library(data.table)
library(psych)
library(plotrix)
library(reshape)
library(corrplot)
library(ggplot2)

# library(forecast)
# library(PerformanceAnalytics)
# library(ggfortify)
# library(dygraphs)
# library(Nclus)
# library(pvclust)
# library(ggplot2)
# library(ggplot)
# library(ROCR)
# library(e1071)
# library(mlbench)
# library(mldeck)
# library(dtw)
# library(plotly)
# library(fpc)
# library(mclust)
# library(xts)
# library(MASS)
# library(caret)
# library(mlbench)
# library(compare)
# library(shiny)
# library(curl)
# library(dplyr)
# library(reshape2)
# library(plyr)
# library(dplyr)
# library(RColorBrewer)


